Redirect output to stderr

diff --git a/git-undo-index b/git-undo-index
--- a/git-undo-index
+++ b/git-undo-index
@@ -29,44 +29,45 @@ COMMIT_MESSAGE="$(git log --format=%s -n 1)"
 GIT_DIFF="$(git diff -- "$@")"
 
 # check if we can go to a new branch
-echo "${COLOR_BOLD}Switching to temp branch: ${TEMP_BRANCH_NAME}${COLOR_RESET}" 1>&2
+#echo "${COLOR_BOLD}Switching to temp branch: ${TEMP_BRANCH_NAME}${COLOR_RESET}" 1>&2
 if ! git checkout -b $TEMP_BRANCH_NAME &>/dev/null; then
+    echo "Unable to create temp branch!" >/dev/stderr
     exit 1
 fi
 
 # actually undo all changes that were specified
-git checkout -- "$@"
+git checkout -- "$@" 1>&2
 #git status
 
 # determine if there are any changes to stash
-USE_STASH="$(git status --short --untracked-files=no)"
+USE_STASH="$(git status --porcelain --untracked-files=no)"
 
 # create a temp stash for changes we're actually keeping
 if [ -n "$USE_STASH" ]; then
-    git stash save "temp stash: ${TEMP_BRANCH_NAME}"
+    git stash save "temp stash: ${TEMP_BRANCH_NAME}" 1>&2
     #git status
 
     # reapply the changes we're keeping so we can keep cherry-pick from the reflog happy
-    git stash apply --index "stash@{0}"
+    git stash apply --index "stash@{0}" 1>&2
     #git status
 
     # commit changes that we're keeping also for cherry-pick purposes
-    git commit -a -m"WIP ${TEMP_BRANCH_NAME}" || true
+    git commit -a -m"WIP ${TEMP_BRANCH_NAME}" 1>&2 || true
     #git status
 fi
 
 # apply the changes we're discarding
-echo "$GIT_DIFF" | git apply
+echo "$GIT_DIFF" | git apply 1>&2
 #git status
 
 # add all the files we're discarding
-echo "${COLOR_BOLD}Adding files to undo:${COLOR_RESET}" 1>&2
+#echo "${COLOR_BOLD}Adding files to undo:${COLOR_RESET}" 1>&2
 git add --verbose --update "$@" 1>&2
 #git status
 
 # commit all the files we're discarding
-echo "${COLOR_BOLD}Creating commit entry for reflog${COLOR_RESET}" 1>&2
-git commit -m"Undoing changes for ${CURRENT_HEAD}: ${COMMIT_MESSAGE} on $(date)" 1>&2
+#echo "${COLOR_BOLD}Creating commit entry for reflog${COLOR_RESET}" 1>&2
+git commit -m"Undoing changes for ${CURRENT_HEAD}: ${COMMIT_MESSAGE} on $(date)"
 #git status
 
 # go back to the previous working branch
@@ -75,7 +76,7 @@ git checkout - 1>&2
 
 # reapply all the changes we're keeping along with the staged state of each file
 if [ -n "$USE_STASH" ]; then
-    git stash pop --index "stash@{0}"
+    git stash pop --index "stash@{0}" 1>&2
     #git status
 fi
 
@@ -86,17 +87,17 @@ git branch -D $TEMP_BRANCH_NAME 1>&2
 # clean up wip reflog entries
 # remove the reflog entry
 if git reflog | grep 'checkout: moving from ' | grep -q " to ${TEMP_BRANCH_NAME}\$"; then
-    echo "${COLOR_BOLD}Removing \"$(git reflog | grep 'checkout: moving from ' | grep " to ${TEMP_BRANCH_NAME}\$" | head -n1 | cut -f3- -d' ')\" from reflog${COLOR_RESET}" 1>&2
+    #echo "${COLOR_BOLD}Removing \"$(git reflog | grep 'checkout: moving from ' | grep " to ${TEMP_BRANCH_NAME}\$" | head -n1 | cut -f3- -d' ')\" from reflog${COLOR_RESET}"
     git reflog delete "$(git reflog | grep 'checkout: moving from ' | grep " to ${TEMP_BRANCH_NAME}\$" | head -n1 | cut -f2 -d' ' | tr -d ':')" 1>&2
 fi
 # remove the reflog entry for the wip commit, as it is not needed
 if git reflog | grep -q "commit: WIP ${TEMP_BRANCH_NAME}\$"; then
-    echo "${COLOR_BOLD}Removing \"$(git reflog | grep "commit: WIP ${TEMP_BRANCH_NAME}\$" | head -n1 | cut -f3- -d' ')\" from reflog${COLOR_RESET}" 1>&2
+    #echo "${COLOR_BOLD}Removing \"$(git reflog | grep "commit: WIP ${TEMP_BRANCH_NAME}\$" | head -n1 | cut -f3- -d' ')\" from reflog${COLOR_RESET}" 1>&2
     git reflog delete "$(git reflog | grep "commit: WIP ${TEMP_BRANCH_NAME}\$" | head -n1 | cut -f2 -d' ' | tr -d ':')" 1>&2
 fi
 # DO NOT DELETE THIS REFLOG ENTRY
 # deleting this entry will rewrite the "Undoing changes for" commit to the current HEAD instead
 #if git reflog | grep -q "checkout: moving from ${TEMP_BRANCH_NAME} to"; then
-#    echo "${COLOR_BOLD}Removing \"$(git reflog | grep "checkout: moving from ${TEMP_BRANCH_NAME} to" | head -n1 | cut -f3- -d' ')\" from reflog${COLOR_RESET}" 1>&2
+#    #echo "${COLOR_BOLD}Removing \"$(git reflog | grep "checkout: moving from ${TEMP_BRANCH_NAME} to" | head -n1 | cut -f3- -d' ')\" from reflog${COLOR_RESET}" 1>&2
 #    git reflog delete "$(git reflog | grep "checkout: moving from ${TEMP_BRANCH_NAME} to" | head -n1 | cut -f2 -d' ' | tr -d ':')" 1>&2
 #fi
